# Generated by Django 6.0.4 on 2026-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_descrioption', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
